import {MODES,escapeHTML as E,textKey,dayKey,normalizeWord,validatePack,validateManifest,legacyWords,mergeWords,shuffle,progressFor,chooseWords,choicesFor,uniquePairs,makeJourney,parseBulk,streak,zipStore,grade,award,safeAsset} from './core.js?v=1.0.0';
import {openStore,compressImage} from './store.js?v=1.0.0';
import {rabbitMarkup} from '../bunny-art.js?v=14.0.0';
const ROOT=new URL('../',import.meta.url), DEMO=new URLSearchParams(location.search).get('demo')==='1';
const $=(s,r=document)=>r.querySelector(s), main=$('#studioMain'), dialog=$('#studioDialog');
const S={view:'home',base:[],words:[],entries:[],images:new Map(),progress:new Map(),profile:{stars:0,days:{}},settings:{sound:true,level:1},packs:new Map(),manifest:null,catalogComplete:false,pack:'all',query:'',category:'all',limit:60,store:null,session:null,parent:false,notes:[],urls:new Map(),preview:null,timer:0,audio:null,confirm:null};
let audioContext,focusBeforeDialog,toastTimer,broadcast;
const PATHS={home:'M3 11 12 3l9 8M5 10v11h14V10M9 21v-7h6v7',book:'M3 4c4-1 6 0 9 2 3-2 5-3 9-2v15c-4-1-6 0-9 2-3-2-5-3-9-2zM12 6v15',game:'M7 7h10c4 0 6 10 3 12-2 1-4-3-5-3H9c-1 0-3 4-5 3C1 17 3 7 7 7zM6 10v5M3.5 12.5h5M16 11h.1M19 14h.1',image:'M3 3h18v18H3zM3 17l6-6 5 5 3-3 4 4M15 7h.1',sound:'M3 9h4l5-4v14l-5-4H3zM16 8q5 4 0 8M19 4q9 8 0 16',cards:'M3 3h7v12H3zM14 9h7v12h-7zM14 3h7M3 21h7',blocks:'M3 3h7v7H3zM14 3h7v7h-7zM8 14h8v7H8z',pencil:'m3 21 2-6L17 3l4 4L9 19zM14 6l4 4',check:'m4 7 3 3 5-6M15 16l6 6M21 16l-6 6',flag:'M5 22V3c4-4 10 4 15 0v11c-5 4-11-4-15 0',chart:'M4 20V11M12 20V4M20 20V8M2 22h20',back:'M20 12H4m7-7-7 7 7 7',plus:'M12 4v16M4 12h16',arrow:'M4 12h16m-7-7 7 7-7 7',refresh:'M20 7v6h-6M4 17v-6h6M5 7a8 8 0 0 1 13-2l2 8M4 11l2 8a8 8 0 0 0 13-2',gear:'M4 7h16M4 17h16M8 4v6M16 14v6',close:'M5 5l14 14M19 5 5 19',upload:'M12 16V3m-5 5 5-5 5 5M3 15v6h18v-6',download:'M12 3v13m-5-5 5 5 5-5M3 17v4h18v-4',search:'M15 15l6 6M18 10a8 8 0 1 1-16 0 8 8 0 0 1 16 0',spark:'m12 2 3 7 7 3-7 3-3 7-3-7-7-3 7-3z'};
function icon(id){return `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${PATHS[id]||PATHS.spark}"/></svg>`;}
const bunny=(mood='idle')=>rabbitMarkup({mood,label:'흰 토끼 토리'});
const action=(name,label,kind='secondary',extra='')=>`<button type="button" class="ws-btn ${kind}" data-action="${name}" ${extra}>${label}</button>`;
function toast(message){clearTimeout(toastTimer);const el=$('#studioToast');el.textContent=message;el.classList.add('visible');toastTimer=setTimeout(()=>el.classList.remove('visible'),4200);}
function issue(e){toast(e?.message||'잠시 문제가 생겼어요. 다시 시도해 주세요.');}
function header(){const stars=Number(S.profile.stars)||0;$('#starCount').textContent=`★ ${stars.toLocaleString()}`;$('#soundButton').innerHTML=icon('sound');$('#soundButton').setAttribute('aria-pressed',String(S.settings.sound));$('#soundButton').setAttribute('aria-label',S.settings.sound?'소리 끄기':'소리 켜기');$('#soundButton').classList.toggle('muted',!S.settings.sound);$('#saveStatus').textContent=S.store?'이 기기 저장':'임시 학습 · 저장 불가';document.body.dataset.scene=S.settings.scene||'garden';}
function resolveAsset(value){return safeAsset(value)?new URL(value,ROOT).href:'';}
function imageURL(w){return w.localImage?S.urls.get(w.id)||'':resolveAsset(w.image);}
function art(w,cls=''){const src=imageURL(w);return `<div class="ws-word-art ${cls}" data-fallback="${E(w.emoji||'✨')}">${src?`<img src="${E(src)}" alt="단어를 떠올려 볼 그림" loading="lazy" decoding="async" referrerpolicy="no-referrer">`:`<span aria-hidden="true">${E(w.emoji||'✨')}</span>`}</div>`;}
document.addEventListener('error',e=>{if(e.target instanceof HTMLImageElement&&e.target.closest('.ws-word-art')){const el=e.target.parentElement;el.innerHTML=`<span aria-hidden="true">${E(el.dataset.fallback)}</span><small>사진을 불러오지 못했어요</small>`;const clue=$('[data-photo-clue]');if(clue)clue.hidden=false;}},true);
function activeWords(){return S.words.filter(w=>S.pack==='all'||w._packId===S.pack);}
function dueWords(){return chooseWords(activeWords(),S.progress,{count:10000,reviewOnly:true});}
function packSelect(){const opts=new Map();for(const w of S.words){opts.set(w._packId,S.packs.get(w._packId)?.pack.title||(w._packId==='legacy'?'기존 단어장':'내가 만든 단어'));}return `<label class="ws-pack-label">학습할 단어장<select id="packSelect" aria-label="학습할 단어장"><option value="all">모든 단어 · ${S.words.length}개</option>${[...opts].map(([id,name])=>`<option value="${E(id)}" ${S.pack===id?'selected':''}>${E(name)}</option>`).join('')}</select></label>`;}
function note(){return S.notes.length?`<details class="ws-notice"><summary>불러오기 안내 ${S.notes.length}건</summary><p>${S.notes.map(E).join('<br>')}</p>${action('reload','다시 불러오기')}</details>`:'';}
function pageHead(kicker,title,aside=''){return `<div class="ws-page-head"><div><p class="ws-kicker">${kicker}</p><h1>${title}</h1></div>${aside}</div>`;}
function render(view=S.view){
  S.view=view;header();document.body.classList.toggle('ws-playing',view==='play');
  document.querySelectorAll('[data-view]').forEach(b=>{if(b.dataset.view===view)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});
  if(view==='home')renderHome();else if(view==='games')renderGames();else if(view==='library')renderLibrary();else if(view==='report')renderReport();else renderQuestion();
  main.scrollTop=0;
}
function renderHome(){
 const words=activeWords(),due=dueWords(),d=S.profile.days?.[dayKey()]||{attempts:0,correct:0},known=words.filter(w=>progressFor(w,S.progress.get(w.id)).box>=3).length;
 main.innerHTML=`${pageHead('A LITTLE EVERY DAY','오늘도, 토리와 한 걸음',packSelect())}${note()}<section class="ws-hero"><div class="ws-hero-copy"><span class="ws-pill">내 단어로 만드는 작은 모험</span><h2>작은 단어가,<br><em>큰 모험이 돼!</em></h2><p>사진으로 만나고, 놀이로 익히고.<br>오늘은 단어 ${Math.min(5,words.length)}개와 친구가 되어 볼까?</p><div class="ws-hero-actions">${action('journey',`오늘의 모험 ${icon('arrow')}`,'primary',words.length?'':'disabled')}${action('review',`다시 만날 단어 ${due.length}개`,'ghost',due.length?'':'disabled')}</div><div class="ws-steps"><span><b>1</b> 보고 듣고</span><span><b>2</b> 놀고</span><span><b>3</b> 기억해요</span></div></div><div class="ws-hero-world"><div class="ws-cloud cloud-one"></div><div class="ws-cloud cloud-two"></div><span class="ws-world-word">hello!</span><div class="ws-hero-bunny">${bunny('wave')}</div><span class="ws-flower f1">✿</span><span class="ws-flower f2">✿</span><div class="ws-hill"></div><span class="ws-world-note">오늘도 같이 해 보자!</span></div></section><div class="ws-home-bottom"><section class="ws-today"><div class="ws-section-title"><h2>차곡차곡 쌓인 발자국</h2><span>오늘</span></div><div class="ws-stat-grid"><div><b>${d.attempts}</b><span>도전한 문제</span></div><div><b>${d.correct}</b><span>스스로 맞힌 문제</span></div><div><b>${known}</b><span>익숙해진 단어</span></div></div></section><button class="ws-create-card" data-action="parent"><span class="ws-create-icon">${icon('image')}</span><span><small>우리 아이만의 단어장</small><strong>단어와 사진을 넣어 주세요</strong><em>직접 등록 · 여러 개 붙여넣기 · GitHub</em></span>${icon('arrow')}</button></div><div class="ws-section-title"><h2>어떤 놀이부터 할까?</h2><button class="ws-text-btn" data-view="games">놀이 모두 보기 →</button></div><div class="ws-mode-grid ws-home-modes">${MODES.slice(0,4).map(modeCard).join('')}</div>`;
}
function modeCard(m){return `<button class="ws-mode mode-${m.id}" data-action="mode" data-mode="${m.id}"><span class="ws-mode-icon">${icon(m.icon)}</span><strong>${m.title}</strong><small>${m.text}</small><span class="ws-mode-arrow">↗</span></button>`;}
function renderGames(){main.innerHTML=`${pageHead('PLAY YOUR WORDS','같은 단어, 여덟 가지 놀이',packSelect())}<div class="ws-game-guide"><div><strong>속도보다, 기억하는 재미.</strong><p>틀려도 괜찮아. 힌트를 보고 다시 만나면 돼!</p></div><label>나에게 맞게<select id="levelSelect"><option value="1" ${S.settings.level===1?'selected':''}>처음이에요 · 보기 2개</option><option value="2" ${S.settings.level===2?'selected':''}>차근차근 · 보기 4개</option><option value="3" ${S.settings.level===3?'selected':''}>도전할래요 · 직접 쓰기</option></select></label></div><div class="ws-mode-grid">${MODES.map(modeCard).join('')}</div><div class="ws-card-strip"><div>${icon('cards')}<span><strong>먼저 보고 들을래요</strong><small>정답 부담 없이 카드를 넘기며 만나기</small></span></div>${action('cards','단어 카드 열기')}</div>`;}
function renderLibrary(){main.innerHTML=`${pageHead('MY WORD COLLECTION','내 단어, 내 사진',action('parent',`${icon('plus')} 단어·사진 관리`,'primary'))}<p class="ws-subtitle">사진을 넣으면 그림 퀴즈와 카드, 철자 놀이에 함께 나와요.</p><div class="ws-library-toolbar">${packSelect()}<label class="ws-search">${icon('search')}<input id="wordSearch" placeholder="단어, 뜻, 주제 검색" value="${E(S.query)}" aria-label="단어 검색" autocomplete="off"></label></div><div id="wordGrid" class="ws-word-grid"></div><div id="wordGridMore"></div>`;renderWordGrid();}
function renderWordGrid(){const filtered=activeWords().filter(w=>textKey(`${w.word} ${w.meaning} ${w.category}`).includes(textKey(S.query)));const grid=$('#wordGrid');if(!grid)return;grid.innerHTML=filtered.length?filtered.slice(0,S.limit).map(w=>{const p=progressFor(w,S.progress.get(w.id));return `<article class="ws-word"><button data-action="single-card" data-id="${E(w.id)}" class="ws-word-open" aria-label="${E(w.word)} 카드 열기">${art(w)}<span class="ws-word-copy"><small>${E(w.category)}</small><strong lang="en">${E(w.word)}</strong><span>${E(w.meaning)}</span></span></button><div class="ws-word-foot"><span class="ws-mastery" title="복습 단계 ${p.box}/5">${Array.from({length:5},(_,i)=>`<i class="${i<p.box?'on':''}"></i>`).join('')}</span><button class="ws-icon-btn" data-action="speak-word" data-id="${E(w.id)}" aria-label="${E(w.word)} 발음 듣기">${icon('sound')}</button><button class="ws-icon-btn" data-action="edit" data-id="${E(w.id)}" aria-label="${E(w.word)} 수정">${icon('pencil')}</button></div></article>`;}).join(''):`<div class="ws-empty"><h2>아직 만날 단어가 없어요.</h2><p>검색어를 바꾸거나, 첫 단어와 사진을 넣어 주세요.</p>${action('parent','단어 넣기','primary')}</div>`;$('#wordGridMore').innerHTML=filtered.length>S.limit?action('more',`${filtered.length-S.limit}개 더 보기`):`<p class="ws-count-note">${filtered.length}개 · 기기 편집 내용이 GitHub 단어보다 우선 표시돼요.</p>`;}
function renderReport(){const words=activeWords(),due=dueWords(),p=S.profile,days=[];for(let i=6;i>=0;i--){const d=new Date();d.setDate(d.getDate()-i);days.push({date:dayKey(d.getTime()),label:['일','월','화','수','목','금','토'][d.getDay()]});}const max=Math.max(5,...days.map(d=>p.days?.[d.date]?.attempts||0)),known=words.filter(w=>progressFor(w,S.progress.get(w.id)).box>=3).length;main.innerHTML=`${pageHead('LITTLE STEPS, BIG GROWTH','내가 남긴 발자국',packSelect())}<div class="ws-report-hero"><div class="ws-report-bunny">${bunny((p.stars||0)>=30?'celebrate':'wave')}</div><div><span class="ws-pill">토리와 ${streak(p.days)}일째 한 걸음</span><h2>어제보다 익숙해지고 있어!</h2><p>별 ${p.stars||0}개 · 익숙해진 단어 ${known}개 · 복습할 단어 ${due.length}개</p><small>이 놀이터의 별과 기록이에요. 기존 모험의 점수·쿠키는 바꾸지 않아요.</small></div></div><section class="ws-report-panel"><div class="ws-section-title"><h2>최근 일주일</h2><span>도전한 문제 수</span></div><div class="ws-bars">${days.map(d=>{const n=p.days?.[d.date]?.attempts||0;return `<div><b>${n}</b><i style="height:${Math.max(4,n/max*110)}px"></i><span>${d.label}</span></div>`;}).join('')}</div></section><div class="ws-badges">${[[0,'첫 만남','토리와 시작하기'],[30,'반짝 탐험가','별 30개 모으기'],[90,'단어 친구','별 90개 모으기'],[180,'기억의 마법사','별 180개 모으기']].map(([n,t,d])=>`<div class="${(p.stars||0)>=n?'unlocked':''}">${icon('spark')}<strong>${t}</strong><small>${d}</small></div>`).join('')}</div><section class="ws-report-panel"><div class="ws-section-title"><h2>다시 만나면 좋은 단어</h2>${action('review','복습하기','primary',due.length?'':'disabled')}</div><div class="ws-review-list">${due.slice(0,12).map(w=>`<span><b>${E(w.word)}</b> ${E(w.meaning)}</span>`).join('')||'<p>지금 복습할 단어는 없어요. 내일 또 만나자!</p>'}</div><p class="ws-fine">복습은 정답·힌트 사용에 따라 1·3·7·14·30일 간격으로 배정해요. 같은 날 반복 정답으로 단계가 계속 올라가지는 않아요. 기기 날짜를 기준으로 해요.</p></section>${action('parent','백업·복원과 GitHub 관리')}`;}
function stopAudio(){try{speechSynthesis.cancel();}catch{}if(S.audio){S.audio.pause();S.audio=null;}}
function speak(w){if(!w)return;stopAudio();if(!S.settings.sound){toast('오른쪽 위 소리를 켜 주세요.');return;}const fallback=()=>{if(!('speechSynthesis'in window)||!('SpeechSynthesisUtterance'in window)){toast('이 기기에서는 발음을 지원하지 않아요. 뜻 힌트로 학습해 주세요.');return;}const u=new SpeechSynthesisUtterance(w.word);u.lang='en-US';u.rate=.82;u.pitch=1;const voice=speechSynthesis.getVoices().find(v=>/^en[-_]/i.test(v.lang));if(voice)u.voice=voice;u.onerror=e=>{if(!['interrupted','canceled'].includes(e.error))toast('발음 재생이 어려워요. 다시 듣거나 뜻 힌트를 눌러 주세요.');};speechSynthesis.speak(u);};const src=resolveAsset(w.audio);if(src){S.audio=new Audio(src);S.audio.play().catch(fallback);}else fallback();}
function chime(good){if(!S.settings.sound)return;try{const C=window.AudioContext||window.webkitAudioContext;if(!C)return;audioContext ||= new C();audioContext.resume().catch(()=>{});const o=audioContext.createOscillator(),g=audioContext.createGain(),now=audioContext.currentTime;o.type='sine';o.frequency.setValueAtTime(good?660:260,now);o.frequency.exponentialRampToValueAtTime(good?990:220,now+.15);g.gain.setValueAtTime(.0001,now);g.gain.exponentialRampToValueAtTime(.04,now+.01);g.gain.exponentialRampToValueAtTime(.0001,now+.25);o.connect(g);g.connect(audioContext.destination);o.start();o.stop(now+.3);}catch{}}
async function persistAttempt(w,correct,mode,hinted=false){let result;if(S.store){try{result=await S.store.attempt(w,correct,mode,hinted);}catch(e){S.notes.push('이번 학습 기록을 저장하지 못했어요. 저장 공간과 브라우저 설정을 확인해 주세요.');toast('기록 저장 실패 · 이번 문제는 임시 기록이에요.');}}if(!result)result={progress:grade(w,S.progress.get(w.id),correct,{hinted}),profile:award(S.profile,w,mode,correct,hinted)};S.progress.set(w.id,result.progress);S.profile=result.profile;header();broadcast?.postMessage('changed');return result.profile.earned||0;}
function sessionHeader(s){return `<div class="ws-session-head">${action('exit','← 나가기','quiet')}<span>${E(s.title)}</span><b>${s.mode==='pairs'?`${s.pairs.matched.size}/${s.pairs.items.length}`:`${Math.min(s.index+1,s.queue.length)}/${s.queue.length}`}</b></div><div class="ws-session-progress"><i style="width:${s.mode==='pairs'?s.pairs.matched.size/s.pairs.items.length*100:s.index/s.queue.length*100}%"></i></div>`;}
function startSession(mode,custom=null){
 const pool=custom||activeWords();if(!pool.length){toast('먼저 단어를 넣어 주세요.');return;}
 const meta=MODES.find(m=>m.id===mode);if(meta?.min>pool.length){toast(`이 놀이는 단어가 ${meta.min}개 이상 필요해요. 카드나 철자 놀이부터 해 봐요.`);return;}
 const chosen=mode==='journey'?chooseWords(pool,S.progress,{count:5}):mode==='review'?chooseWords(pool,S.progress,{count:10,reviewOnly:true}):shuffle(pool).slice(0,mode==='card'?20:10);
 if(!chosen.length){toast('지금 복습할 단어가 없어요. 잘했어!');return;}
 stopAudio();clearTimeout(S.timer);
 const title=mode==='journey'?'오늘의 모험':mode==='review'?'다시 만나는 단어':mode==='card'?'보고 듣는 카드':meta?.title||'단어 놀이';
 const s=S.session={mode,title,pool,queue:[],index:0,locked:false,awaiting:false,attempts:0,correct:0,stars:0,combo:0,wrong:new Set(),retries:new Map(),lastAdvance:0};
 if(mode==='pairs'){const items=uniquePairs(pool,4);if(items.length<2){S.session=null;toast('서로 다른 단어와 뜻이 2쌍 이상 필요해요.');return;}s.pairs={items,left:shuffle(items),right:shuffle(items),matched:new Set(),a:null,b:null};}
 else if(mode==='journey')s.queue=makeJourney(chosen,pool,S.settings.level);
 else s.queue=chosen.map((w,i)=>({word:w,mode:mode==='trail'?['picture','meaning','ox','tiles'][i%4]:mode==='review'?'picture':mode}));
 render('play');main.focus({preventScroll:true});
}
function renderQuestion(){
 const s=S.session;if(!s){render('games');return;}if(s.mode==='pairs'){renderPairs();return;}if(s.index>=s.queue.length){finish();return;}
 const q=s.queue[s.index],w=q.word;s.locked=false;s.awaiting=false;q.hinted=false;q.selected=[];
 const count=S.settings.level===1?2:4;let content='',answer='';
 if(q.mode==='card')content=`${art(w,'large')}<h1 lang="en">${E(w.word)}</h1><p class="ws-meaning">${E(w.meaning)}</p>${w.example?`<div class="ws-example"><b lang="en">${E(w.example)}</b><span>${E(w.exampleMeaning)}</span></div>`:''}<div class="ws-card-actions">${action('card-again','한 번 더 볼래요')}${action('card-next','기억했어요 →','primary')}</div>`;
 else if(q.mode==='picture'||q.mode==='meaning'||q.mode==='listen'){
   const key=q.mode==='meaning'?'meaning':'word';q.options=choicesFor(w,s.pool,key,count);
   if(q.options.length<2){q.mode='tiles';renderQuestion();return;}
   if(q.mode==='picture')content=`${art(w,'large')}<p class="ws-meaning" data-photo-clue ${imageURL(w)&&S.settings.level>1?'hidden':''}>${E(w.meaning)}</p><p class="ws-prompt">어떤 영어 단어일까?</p>`;
   if(q.mode==='meaning')content=`<span class="ws-question-label">이 단어는 어떤 뜻일까?</span><h1 lang="en">${E(w.word)}</h1>`;
   if(q.mode==='listen')content=`<button class="ws-listen-orb" data-action="speak-current" aria-label="영어 단어 발음 듣기">${icon('sound')}</button><h1 class="ws-listen-title">귀를 쫑긋!</h1><p class="ws-prompt">다시 듣기는 큰 소리 버튼을 눌러 줘.</p><p class="ws-revealed-hint" id="listenHint" hidden>${E(w.meaning)}</p>${action('listen-hint','소리가 안 들려요 · 뜻 힌트','quiet')}`;
   answer=`<div class="ws-choices">${q.options.map(option=>`<button data-action="answer-choice" data-id="${E(option.id)}" ${key==='word'?'lang="en"':''}>${E(option[key])}</button>`).join('')}</div>`;
 }else if(q.mode==='ox'){
   const alt=choicesFor(w,s.pool,'meaning',2).find(x=>x.id!==w.id);q.claim=alt&&Math.random()<.5?alt:w;q.truth=textKey(q.claim.meaning)===textKey(w.meaning);
   content=`${art(w)}<h1 lang="en">${E(w.word)}</h1><p class="ws-meaning">${E(q.claim.meaning)}</p><p class="ws-prompt">단어와 뜻이 서로 맞을까?</p>`;answer=`<div class="ws-ox">${action('answer-ox','<b>O</b><span>맞아요</span>','', 'data-value="true"')}${action('answer-ox','<b>X</b><span>아니에요</span>','', 'data-value="false"')}</div>`;
 }else{
   content=`${art(w)}<p class="ws-meaning">${E(w.meaning)}</p><p class="ws-prompt">${q.mode==='type'?'기억나는 영어 단어를 써 봐!':'글자를 차례대로 눌러 줘!'}</p>`;
   if(q.mode==='tiles'){q.letters=shuffle(Array.from(w.word).map((letter,i)=>({letter,i})));answer=`<div id="tileSlots" class="ws-tile-slots" aria-live="polite"><span>글자를 눌러 단어를 만들어요</span></div><div class="ws-tiles">${q.letters.map((l,i)=>`<button data-action="tile" data-index="${i}" aria-label="${l.letter===' '?'띄어쓰기':E(l.letter)}">${l.letter===' '?'␣':E(l.letter)}</button>`).join('')}</div><div class="ws-answer-tools">${action('tile-undo','← 하나 지우기','quiet')}${action('hint','힌트 보기','quiet')}${action('answer-tiles','확인','primary')}</div>`;}
   else answer=`<form id="typeForm" class="ws-type-form"><label class="ws-sr-only" for="typeAnswer">영어 단어 입력</label><input id="typeAnswer" name="typeAnswer" lang="en" inputmode="text" autocomplete="off" autocorrect="off" autocapitalize="none" spellcheck="false" maxlength="60" placeholder="영어 단어를 써 주세요"><button class="ws-btn primary" type="submit">확인</button></form>${action('hint','힌트 보기','quiet')}`;
 }
 main.innerHTML=`<div class="ws-play-shell">${sessionHeader(s)}${s.mode==='trail'?`<div class="ws-trail" aria-label="보물길 진행"><span style="left:${Math.min(90,s.index/Math.max(1,s.queue.length-1)*90)}%">${bunny('wave')}</span>${'<i></i>'.repeat(10)}<b>★</b></div>`:''}<div class="ws-question-layout"><aside class="ws-play-buddy">${bunny('idle')}<p>틀려도 괜찮아.<br>우리 같이 기억하자!</p><span id="comboLabel">${s.combo?`${s.combo}번 연속 성공!`:'차근차근 한 걸음'}</span></aside><section class="ws-question" data-word-id="${E(w.id)}" data-mode="${q.mode}"><div class="ws-question-top"><span>${q.retry?'다시 만나 반가워!':q.mode==='card'?'먼저 보고 들어요':'생각을 꺼내 봐요'}</span><button class="ws-icon-btn" data-action="speak-current" aria-label="현재 단어 발음 듣기">${icon('sound')}</button></div>${content}<div class="ws-answer-zone">${answer}</div><div id="questionFeedback" class="ws-feedback" role="status" aria-live="polite"></div></section></div></div>`;
 if(q.mode==='listen')S.timer=setTimeout(()=>{if(S.session===s&&s.queue[s.index]===q)speak(w);},250);
}
async function answer(correct){const s=S.session,q=s?.queue[s.index];if(!q||s.locked||q.mode==='card')return;s.locked=true;clearTimeout(S.timer);const points=await persistAttempt(q.word,correct,q.mode,q.hinted);if(S.session!==s)return;s.attempts++;s.correct+=correct&&!q.hinted?1:0;s.stars+=points;s.combo=correct&&!q.hinted?s.combo+1:0;if(!correct||q.hinted){s.wrong.add(q.word.id);const n=s.retries.get(q.word.id)||0;if(n<2&&s.queue.length<45){s.retries.set(q.word.id,n+1);s.queue.splice(Math.min(s.index+3,s.queue.length),0,{word:q.word,mode:q.mode,retry:true});}}
 const el=$('#questionFeedback');if(!el)return;el.className=`ws-feedback ${correct?'good':'review'}`;el.innerHTML=`<div><b>${correct?(q.hinted?'힌트와 함께 해냈어!':'맞았어! 잘했어!'):'괜찮아, 다시 만나면 돼!'}</b><span><strong lang="en">${E(q.word.word)}</strong> · ${E(q.word.meaning)}${points?` · ★ +${points}`:''}</span></div>${action('next-question',correct?'다음 →':'기억하고 다음 →','primary')}`;$('.ws-question').classList.add(correct?'ws-correct':'ws-review');$('.ws-play-buddy')?.querySelectorAll('.bunny-rabbit').forEach(b=>b.dataset.mood=correct?'celebrate':'review');document.querySelectorAll('.ws-answer-zone button,.ws-answer-zone input').forEach(b=>b.disabled=true);s.awaiting=true;chime(correct);if(correct&&!q.hinted)S.timer=setTimeout(nextQuestion,1300);}
function nextQuestion(){const s=S.session;if(!s||!s.awaiting)return;clearTimeout(S.timer);s.awaiting=false;s.index++;stopAudio();renderQuestion();}
function cardNext(again=false){const s=S.session,q=s?.queue[s.index];if(!q||q.mode!=='card'||s.locked)return;s.locked=true;if(again&&(s.retries.get(q.word.id)||0)<1){s.retries.set(q.word.id,1);s.queue.push({...q,retry:true});}s.index++;stopAudio();renderQuestion();}
function renderPairs(){const s=S.session,p=s.pairs;s.locked=false;main.innerHTML=`<div class="ws-play-shell">${sessionHeader(s)}<div class="ws-pairs-heading"><h1>단어와 뜻을 짝지어 줘!</h1><p>왼쪽 하나, 오른쪽 하나를 눌러요.</p></div><div class="ws-pairs-board">${['left','right'].map(side=>`<div>${p[side].map(w=>`<button class="ws-pair ${p.matched.has(w.id)?'matched':''}" data-action="pair" data-side="${side}" data-id="${E(w.id)}" ${p.matched.has(w.id)?'disabled':''}>${side==='left'?`<b lang="en">${E(w.word)}</b>`:`${art(w)}<span>${E(w.meaning)}</span>`}</button>`).join('')}</div>`).join('')}</div><div id="pairFeedback" class="ws-pair-feedback" role="status" aria-live="polite">토리도 함께 찾고 있어요.</div></div>`;}
async function selectPair(button){const s=S.session,p=s?.pairs;if(!p||s.locked)return;const side=button.dataset.side==='left'?'a':'b';p[side]=button.dataset.id;document.querySelectorAll(`[data-side="${button.dataset.side}"]`).forEach(b=>b.classList.toggle('selected',b===button));if(!p.a||!p.b)return;s.locked=true;const w=p.items.find(x=>x.id===p.a),correct=p.a===p.b,points=await persistAttempt(w,correct,'pairs');if(S.session!==s)return;s.attempts++;s.correct+=correct?1:0;s.stars+=points;if(correct)p.matched.add(w.id);else s.wrong.add(w.id);$('#pairFeedback').textContent=correct?'짝꿍을 찾았어!':'다른 짝꿍이네. 천천히 다시 골라 보자.';chime(correct);S.timer=setTimeout(()=>{if(S.session!==s)return;p.a=null;p.b=null;if(p.matched.size===p.items.length)finish();else renderPairs();},correct?650:1050);}
function finish(){const s=S.session;if(!s)return;stopAudio();clearTimeout(S.timer);s.finished=true;const accuracy=s.attempts?Math.round(s.correct/s.attempts*100):null;main.innerHTML=`<section class="ws-result"><div class="ws-result-bunny">${bunny('celebrate')}</div><span class="ws-pill">끝까지 함께했어!</span><h1>${s.mode==='card'?'단어들과 인사 완료!':'오늘의 한 걸음, 성공!'}</h1><p>모르는 단어를 다시 만나는 것도 멋진 공부야.</p><div class="ws-result-stats"><span><b>★ ${s.stars}</b>이번에 얻은 별</span><span><b>${accuracy===null?'—':`${accuracy}%`}</b>힌트 없이 맞힌 비율</span><span><b>${s.wrong.size}</b>다시 만날 단어</span></div>${s.wrong.size?`<div class="ws-result-words">${[...s.wrong].slice(0,10).map(id=>`<span>${E(S.words.find(w=>w.id===id)?.word||'')}</span>`).join('')}</div>`:''}<div class="ws-result-actions">${s.wrong.size?action('retry-wrong','이 단어들 한 번 더','primary'):action('to-home','오늘 화면으로','primary')}${action('to-games','다른 놀이 하기')}</div><p class="ws-fine">별은 같은 날 같은 단어·놀이의 첫 정답에만 받아요.${S.store?' 기록은 이 브라우저에 저장돼요.':' 지금은 임시 기록이에요. 저장 설정을 확인해 주세요.'}</p></section>`;}
function showModal(html){focusBeforeDialog=document.activeElement;$('#studioModal').innerHTML=html;if(!dialog.open)dialog.showModal();requestAnimationFrame(()=>dialog.querySelector('input:not([type=hidden]),button')?.focus());}
function modalHead(title,desc=''){return `<div class="ws-modal-head"><div><h2 id="modalTitle">${title}</h2>${desc?`<p>${desc}</p>`:''}</div><button type="button" class="ws-icon-btn" data-action="close-modal" aria-label="닫기">${icon('close')}</button></div>`;}
dialog.addEventListener('close',()=>{if(S.preview){URL.revokeObjectURL(S.preview);S.preview=null;}focusBeforeDialog?.isConnected&&focusBeforeDialog.focus({preventScroll:true});});
function requireParent(next){if(S.parent){next();return;}const a=3+Math.floor(Math.random()*7),b=4+Math.floor(Math.random()*8);S.gate={answer:a+b,next};showModal(`${modalHead('보호자와 함께 열어요','이 기기의 편집 도구를 여는 간단한 확인이에요. 계정 보안용 비밀번호는 아니에요.')}<form id="gateForm"><label class="ws-field">${a} + ${b} = ?<input name="answer" inputmode="numeric" autocomplete="off" required aria-label="덧셈 정답"></label><p id="gateError" class="ws-form-error" role="alert"></p><button class="ws-btn primary" type="submit">편집 도구 열기</button></form>`);}
function manage(){showModal(`${modalHead('우리 아이 단어 공방','직접 만든 단어와 사진으로 모든 놀이를 즐겨요.')}<div class="ws-manage-actions">${action('add',`${icon('plus')} 단어·사진 하나 추가`,'primary')}${action('bulk',`${icon('cards')} 여러 단어 붙여넣기`)}${action('import',`${icon('upload')} JSON 가져오기·백업 복원`)}${action('backup',`${icon('download')} 단어 놀이터 전체 백업`)}${action('github-confirm',`${icon('download')} GitHub 업데이트 ZIP 만들기`)}${action('reload',`${icon('refresh')} GitHub 최신 단어 불러오기`)}</div><div class="ws-privacy"><strong>기기 저장과 GitHub 저장은 달라요.</strong><p>여기서 등록한 사진과 단어는 이 브라우저에 저장돼요. GitHub에는 자동 전송하지 않아요. ZIP을 ChatGPT에 전달해 저장소에 반영하면 다른 기기에서도 볼 수 있어요.</p><p>이 저장소는 공개 저장소예요. 아이 얼굴·이름·학교 등 개인정보가 담긴 사진은 GitHub에 올리지 마세요.</p></div><a class="ws-doc-link" href="https://github.com/dalmook/heather_word/blob/main/WORD_STUDIO_GUIDE.md" target="_blank" rel="noopener noreferrer">GitHub·ChatGPT 업데이트 안내 ↗</a><p class="ws-fine">기존 단어·카테고리·Firebase·쿠키·수집 기록은 바꾸지 않아요. 새 놀이터의 기록과 기기 사진은 별도 백업해 주세요.</p>`);}
function editor(id){const w=S.words.find(x=>x.id===id)||{id:'',word:'',meaning:'',category:'내 단어',emoji:'✨',example:'',exampleMeaning:'',image:'',audio:''};S.editOriginal=w;showModal(`${modalHead(id?'단어와 사진 수정':'새 단어 만나기','사진은 최대 1,024px로 줄여 저장해요. 원본 파일은 바꾸지 않아요.')}<form id="wordForm"><input type="hidden" name="id" value="${E(w.id)}"><div class="ws-editor-top"><div class="ws-photo-preview" id="photoPreview">${art(w)}</div><label class="ws-upload-box">${icon('image')}<strong>사진 고르기</strong><span>JPG · PNG · WebP · GIF / 15MB 이하</span><input id="photoInput" name="photo" type="file" accept="image/jpeg,image/png,image/webp,image/gif"></label></div><label class="ws-check-row"><input type="checkbox" name="removeImage"> 기존 사진 제거</label><div class="ws-form-grid"><label class="ws-field">영어 단어<input name="word" value="${E(w.word)}" maxlength="60" required placeholder="apple" autocapitalize="none" spellcheck="false"></label><label class="ws-field">한글 뜻<input name="meaning" value="${E(w.meaning)}" maxlength="120" required placeholder="사과"></label><label class="ws-field">주제·단원<input name="category" value="${E(w.category)}" maxlength="40" placeholder="학교 숙제 1일차"></label><label class="ws-field">사진이 없을 때 아이콘<input name="emoji" value="${E(w.emoji)}" maxlength="12" placeholder="🍎"></label></div><details class="ws-extra-fields"><summary>예문 · 이미지 주소 · 발음 파일 (선택)</summary><label class="ws-field">영어 예문<input name="example" value="${E(w.example)}" maxlength="240" placeholder="I like apples."></label><label class="ws-field">예문 뜻<input name="exampleMeaning" value="${E(w.exampleMeaning)}" maxlength="240" placeholder="나는 사과를 좋아해요."></label><label class="ws-field">GitHub 사진 경로 또는 HTTPS 주소<input name="image" value="${E(w.image)}" placeholder="content/images/apple.webp"></label><label class="ws-field">발음 파일 경로 또는 HTTPS 주소<input name="audio" value="${E(w.audio)}" placeholder="content/audio/apple.mp3"></label></details><p id="wordFormError" class="ws-form-error" role="alert"></p><div class="ws-editor-footer">${id?action('hide-word','이 기기에서 숨기기','quiet',`data-id="${E(id)}"`):'<span></span>'}<button class="ws-btn primary" type="submit">저장하고 놀기 ${icon('arrow')}</button></div>${id&&S.entries.some(x=>x.id===id)?action('reset-word','기기 편집 취소 · 원본으로','quiet',`data-id="${E(id)}"`):''}</form>`);}
function bulkEditor(){showModal(`${modalHead('단어 여러 개 넣기','엑셀에서 복사해 붙이거나, 한 줄에 단어 / 뜻을 적어 주세요.')}<form id="bulkForm"><label class="ws-field">단어 목록<textarea name="text" rows="9" required placeholder="apple / 사과\nbanana / 바나나\n\n엑셀: word [탭] meaning [탭] category [탭] image [탭] example"></textarea></label><p class="ws-fine">CSV와 탭 구분을 지원해요. 최대 500개. 같은 영어·뜻·주제는 중복 추가하지 않아요. 사진은 등록 후 단어별로 넣을 수 있어요.</p><p id="bulkError" class="ws-form-error" role="alert"></p><button type="submit" class="ws-btn primary">목록 확인하고 추가</button></form>`);}
function requireStore(){if(!S.store)throw Error('저장소를 사용할 수 없어요. 브라우저의 사이트 저장 설정을 확인해 주세요.');return S.store;}
async function refreshLocal(){if(S.store){const data=await S.store.snapshot();S.entries=data.entries;S.progress=new Map(data.progress.map(p=>[p.id,p]));S.profile=data.meta.find(x=>x.id==='profile')||{stars:0,days:{}};S.settings={...S.settings,...data.meta.find(x=>x.id==='settings')};for(const url of S.urls.values())URL.revokeObjectURL(url);S.urls.clear();S.images=new Map(data.images.map(x=>[x.id,x.blob]));for(const [id,blob]of S.images)S.urls.set(id,URL.createObjectURL(blob));}S.words=mergeWords(S.base,S.entries);if(S.pack!=='all'&&!S.words.some(w=>w._packId===S.pack))S.pack='all';header();}
async function fetchJSON(url){const c=new AbortController(),timer=setTimeout(()=>c.abort(),9000);try{const r=await fetch(url,{cache:'no-store',signal:c.signal});if(!r.ok)throw Error(`${new URL(url).pathname}: HTTP ${r.status}`);return await r.json();}finally{clearTimeout(timer);}}
async function loadRepository(){
 const manifest=validateManifest(await fetchJSON(new URL('content/index.json',ROOT)));const packs=new Map(),ids=new Set();let complete=true;const notes=[];
 for(const item of manifest.packs){try{const pack=validatePack(await fetchJSON(new URL(`content/${item.file}`,ROOT)));if(pack.id!==item.id)throw Error('목록의 ID와 단어팩 ID가 달라요.');if(pack.words.some(w=>ids.has(w.id)))throw Error('다른 단어팩과 ID가 중복돼요.');for(const w of pack.words)ids.add(w.id);packs.set(pack.id,{file:item.file,pack});}catch(e){complete=false;notes.push(`${item.id}: ${e.message}`);}}
 return{manifest,packs,complete,notes};
}
function readLegacy(){let snapshot={};try{snapshot=JSON.parse(localStorage.getItem(DEMO?'heather_word_demo_v1':'heather_word_v3')||'{}');}catch{S.notes.push('기존 기기 단어장을 읽지 못했어요. 원본 데이터는 변경하지 않았어요.');}return legacyWords(snapshot);}
async function loadAll(){S.notes=[];let repo;try{repo=await loadRepository();S.manifest=repo.manifest;S.packs=repo.packs;S.catalogComplete=repo.complete;S.notes.push(...repo.notes);if(repo.complete&&S.store)await S.store.setMeta({id:'catalog-cache',manifest:repo.manifest,packs:[...repo.packs.values()]});}catch(e){S.catalogComplete=false;S.notes.push('GitHub 단어를 새로 가져오지 못했어요. 저장된 내용으로 열어요.');const cached=S.store?(await S.store.all('meta')).find(x=>x.id==='catalog-cache'):null;if(cached){S.manifest=cached.manifest;S.packs=new Map(cached.packs.map(x=>[x.pack.id,x]));}}
 const legacy=readLegacy();try{const data=await fetchJSON(new URL('words.json',ROOT));const old=legacyWords(data);const map=new Map([...old,...legacy].map(w=>[w.id,w]));S.base=[...map.values()];}catch{S.base=legacy;}
 for(const {pack}of S.packs.values())S.base.push(...pack.words.map(w=>({...w,_packId:pack.id,_source:pack.sample?'GitHub 체험팩':'GitHub 단어'})));
 await refreshLocal();
}
function download(blob,name){const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),30000);}
function confirmAction(title,message,fn,label='계속하기'){S.confirm=fn;showModal(`${modalHead(title)}<p class="ws-confirm-copy">${message}</p><div class="ws-dialog-actions">${action('close-modal','취소')}${action('confirm',label,'primary')}</div>`);}
async function githubExport(){
 const store=requireStore(),repo=await loadRepository();if(!repo.complete)throw Error('GitHub의 모든 단어팩을 읽지 못해 안전하게 내보낼 수 없어요. 연결 후 다시 시도해 주세요.');
 const data=await store.snapshot(),edits=data.entries.filter(e=>!e.hidden);if(!edits.length)throw Error('먼저 단어를 추가하거나 수정해 주세요.');
 const manifest=structuredClone(repo.manifest),changed=new Map(),files=[],images=new Map(data.images.map(x=>[x.id,x.blob]));
 for(const e of edits){const id=repo.packs.has(e._packId)?e._packId:'my-words';let target=changed.get(id);if(!target){target=repo.packs.has(id)?structuredClone(repo.packs.get(id)):{file:'packs/my-words.json',pack:{schemaVersion:1,id:'my-words',title:'내가 만든 단어',description:'직접 등록한 단어와 사진',words:[]}};changed.set(id,target);if(!manifest.packs.some(p=>p.id===id))manifest.packs.push({id,file:target.file});}
  const w=normalizeWord(e);if(e.localImage){const blob=images.get(e.id);if(!blob)throw Error(`${e.word}: 기기 사진을 찾지 못했어요.`);const ext=blob.type==='image/png'?'png':blob.type==='image/jpeg'?'jpg':'webp';w.image=`content/images/${e.id}.${ext}`;files.push({name:w.image,data:new Uint8Array(await blob.arrayBuffer())});}
  const index=target.pack.words.findIndex(x=>x.id===w.id);if(index<0)target.pack.words.push(w);else target.pack.words[index]=w;
 }
 for(const target of changed.values()){validatePack(target.pack);files.push({name:`content/${target.file}`,data:JSON.stringify(target.pack,null,2)+'\n'});}
 files.push({name:'content/index.json',data:JSON.stringify(manifest,null,2)+'\n'},{name:'README-IMPORT.txt',data:'이 ZIP의 content 폴더를 dalmook/heather_word에 반영하세요. 기존 words.json, 카테고리, 사용자 기록은 변경하지 마세요. content/index.json은 최신 저장소 목록과 병합하고 기존 단어팩을 삭제하지 마세요. 사진은 공개되므로 개인정보와 사용 권리를 확인하세요. node tools/validate-word-studio.mjs 및 npm test로 검증하세요. 앱은 GitHub에 자동 전송하지 않습니다. 기기 학습기록은 별도의 전체 백업 JSON을 이용하세요.\n'});
 download(zipStore(files),`heather-word-github-${dayKey()}.zip`);toast('GitHub용 ZIP을 만들었어요. 아직 GitHub에 전송되지는 않았어요.');
}
async function importJSON(file){if(!file)return;if(file.size>55*1024*1024)throw Error('파일은 55MB 이하로 선택해 주세요.');const value=JSON.parse(await file.text());if(value.format==='heather-word-studio'){const {validateBackup}=await import('./store.js?v=1.0.0');validateBackup(value);confirmAction('백업을 복원할까요?',`${value.entries.length}개 단어와 사진·기록을 이 놀이터에 병합해요. 같은 ID의 단어와 놀이터 기록은 백업 내용으로 바뀝니다. 기존 모험의 기록은 건드리지 않아요.`,async()=>{await requireStore().restore(value);await refreshLocal();render('library');toast('단어 놀이터 백업을 복원했어요.');},'복원하기');}else{const pack=validatePack(value);confirmAction('단어팩을 가져올까요?',`${E(pack.title)} · ${pack.words.length}개. 같은 ID의 기기 편집 내용은 가져온 내용으로 바뀌어요.`,async()=>{await requireStore().saveMany(pack.words.map(w=>({...w,_packId:pack.id})));await refreshLocal();render('library');toast(`${pack.words.length}개 단어를 가져왔어요.`);},'가져오기');}}
async function navigate(view){if(S.session&&!S.session.finished&&S.view==='play'){confirmAction('놀이를 나갈까요?','이미 푼 문제의 기록은 남아요. 아직 풀지 않은 문제는 기록하지 않아요.',()=>{clearTimeout(S.timer);stopAudio();S.session=null;render(view);},'나가기');return;}clearTimeout(S.timer);stopAudio();S.session=null;render(view);}
async function handleAction(button){const a=button.dataset.action,id=button.dataset.id,s=S.session,q=s?.queue[s.index];
 switch(a){
 case 'journey':startSession('journey');break;case 'review':startSession('review');break;case 'cards':startSession('card');break;case 'mode':startSession(button.dataset.mode);break;case 'single-card':startSession('card',[S.words.find(w=>w.id===id)].filter(Boolean));break;
 case 'speak-word':speak(S.words.find(w=>w.id===id));break;case 'speak-current':speak(q?.word);break;
 case 'listen-hint':if(q&&!s.locked){q.hinted=true;$('#listenHint').hidden=false;}break;
 case 'answer-choice':await answer(id===q?.word.id);break;case 'answer-ox':await answer((button.dataset.value==='true')===q?.truth);break;
 case 'tile':if(q&&!s.locked&&!q.selected.includes(Number(button.dataset.index))){q.selected.push(Number(button.dataset.index));button.disabled=true;$('#tileSlots').textContent=q.selected.map(i=>q.letters[i].letter).join('');}break;
 case 'tile-undo':if(q&&!s.locked){const i=q.selected.pop();const b=$(`[data-action="tile"][data-index="${i}"]`);if(b)b.disabled=false;$('#tileSlots').textContent=q.selected.map(j=>q.letters[j].letter).join('')||'글자를 눌러 단어를 만들어요';}break;
 case 'hint':if(q&&!s.locked){q.hinted=true;toast(`힌트: ${q.word.word}`);speak(q.word);}break;
 case 'answer-tiles':await answer(textKey(q?.selected.map(i=>q.letters[i].letter).join(''))===textKey(q?.word.word));break;
 case 'next-question':nextQuestion();break;case 'card-next':cardNext();break;case 'card-again':cardNext(true);break;case 'pair':await selectPair(button);break;
 case 'exit':await navigate('games');break;case 'to-home':await navigate('home');break;case 'to-games':await navigate('games');break;case 'retry-wrong':{const words=S.words.filter(w=>s?.wrong.has(w.id));startSession(words.length>1?'trail':'tiles',words);break;}
 case 'parent':requireParent(manage);break;case 'add':editor();break;case 'edit':requireParent(()=>editor(id));break;case 'bulk':bulkEditor();break;case 'close-modal':dialog.close();break;
 case 'confirm':{const fn=S.confirm;S.confirm=null;dialog.close();if(fn)await fn();break;}
 case 'hide-word':{const w=S.words.find(x=>x.id===id);confirmAction('이 기기에서 숨길까요?',`<b>${E(w.word)}</b>을 이 놀이터에서 숨겨요. GitHub와 기존 단어장은 삭제하지 않아요.`,async()=>{await requireStore().save({...w,hidden:true});dialog.close();await refreshLocal();render('library');toast('이 기기에서 숨겼어요.');},'숨기기');break;}
 case 'reset-word':confirmAction('기기 편집을 취소할까요?','이 단어의 기기 사진·수정을 지우고 GitHub 또는 기존 단어장 내용을 다시 사용해요. 기기에서만 만든 단어는 사라져요.',async()=>{await requireStore().reset(id);await refreshLocal();render('library');},'원본으로');break;
 case 'more':S.limit+=60;renderWordGrid();break;
 case 'backup':{const catalog=[...S.words,...S.entries.filter(e=>e.hidden&&!S.words.some(w=>w.id===e.id))];const backup=await requireStore().backup(catalog);download(new Blob([JSON.stringify(backup)],{type:'application/json'}),`heather-word-backup-${dayKey()}.json`);toast('사진·단어·놀이터 기록을 백업했어요.');break;}
 case 'github-confirm':confirmAction('GitHub용 파일 만들기','공개 GitHub에 반영하면 사진과 단어가 누구에게나 보여요. 아이 얼굴·이름·학교와 저작권을 확인해 주세요.<br><br>ZIP만 만들며 자동 업로드하지는 않아요.',githubExport,'확인했어요 · ZIP 만들기');break;
 case 'import':$('#studioImport').value='';$('#studioImport').click();break;
 case 'reload':dialog.close();await loadAll();render(S.view==='play'?'home':S.view);toast(S.catalogComplete?'GitHub 최신 단어를 확인했어요.':'일부 내용을 불러오지 못했어요. 안내를 확인해 주세요.');break;
 }
}
document.addEventListener('click',e=>{const b=e.target.closest('button[data-action],button[data-view]');if(!b||b.disabled)return;if(b.dataset.view)navigate(b.dataset.view).catch(issue);else handleAction(b).catch(issue);});
document.addEventListener('input',e=>{if(e.target.id==='wordSearch'){S.query=e.target.value;S.limit=60;renderWordGrid();}});
document.addEventListener('change',async e=>{try{const t=e.target;if(t.id==='packSelect'){S.pack=t.value;S.limit=60;render();}if(t.id==='levelSelect'){S.settings.level=Number(t.value);await S.store?.setMeta({id:'settings',...S.settings});}if(t.id==='photoInput'){if(S.preview)URL.revokeObjectURL(S.preview);const f=t.files[0];if(f){if(!/^image\/(jpeg|png|webp|gif)$/.test(f.type)||f.size>15*1024*1024){t.value='';throw Error('15MB 이하의 JPG, PNG, WebP, GIF를 골라 주세요.');}S.preview=URL.createObjectURL(f);$('#photoPreview').innerHTML=`<img src="${S.preview}" alt="등록할 사진 미리보기">`;}}if(t.id==='studioImport')await importJSON(t.files[0]);}catch(err){issue(err);}});
// Use the attribute: a form control named "id" shadows HTMLFormElement.id.
document.addEventListener('submit',async e=>{const form=e.target,formID=form.getAttribute('id');if(!['wordForm','bulkForm','gateForm','typeForm'].includes(formID))return;e.preventDefault();const submit=$('[type=submit]',form);if(submit?.disabled)return;const data=new FormData(form);
 if(formID==='gateForm'){if(Number(data.get('answer'))!==S.gate?.answer){$('#gateError').textContent='한 번 더 계산해 주세요.';return;}S.parent=true;const next=S.gate.next;dialog.close();next();return;}
 if(formID==='typeForm'){await answer(textKey(data.get('typeAnswer')||$('#typeAnswer').value)===textKey(S.session.queue[S.session.index].word.word));return;}
 if(submit)submit.disabled=true;
 try{if(formID==='wordForm'){const old=S.editOriginal,photo=$('#photoInput').files[0],remove=data.get('removeImage')==='on';const w=normalizeWord({id:data.get('id')||`user-${crypto.randomUUID()}`,word:data.get('word'),meaning:data.get('meaning'),category:data.get('category'),emoji:data.get('emoji'),image:remove?'':data.get('image'),audio:data.get('audio'),example:data.get('example'),exampleMeaning:data.get('exampleMeaning')});const duplicate=S.words.find(x=>x.id!==w.id&&textKey(x.word)===textKey(w.word)&&textKey(x.meaning)===textKey(w.meaning)&&textKey(x.category)===textKey(w.category));if(duplicate)throw Error('같은 단어·뜻·주제가 이미 있어요. 기존 단어를 수정해 주세요.');let image=remove?null:undefined;if(photo)image=await compressImage(photo);await requireStore().save({...w,_packId:old._packId||'my-words',localImage:photo?true:remove?false:!!old.localImage},image);dialog.close();await refreshLocal();S.pack='all';S.query=w.word;render('library');toast('저장했어요! 모든 놀이에서 바로 쓸 수 있어요.');}
 else{const parsed=parseBulk(data.get('text')),seen=new Set(S.words.map(w=>`${textKey(w.word)}|${textKey(w.meaning)}|${textKey(w.category)}`)),rows=[];for(const w of parsed){const k=`${textKey(w.word)}|${textKey(w.meaning)}|${textKey(w.category)}`;if(seen.has(k))continue;seen.add(k);rows.push({...w,id:`user-${crypto.randomUUID()}`});}if(!rows.length)throw Error('추가할 새 단어가 없어요. 중복 여부를 확인해 주세요.');const count=rows.length;confirmAction('새 단어를 추가할까요?',`${count}개를 추가해요. 중복 ${parsed.length-count}개는 건너뛰어요.`,async()=>{await requireStore().saveMany(rows);await refreshLocal();S.pack='all';S.query='';render('library');toast(`${count}개 단어를 추가했어요.`);},'추가하기');}
 broadcast?.postMessage('changed');
 }catch(err){const el=$(formID==='wordForm'?'#wordFormError':'#bulkError');if(el)el.textContent=err.message;else issue(err);}finally{if(submit?.isConnected)submit.disabled=false;}});
$('#soundButton').addEventListener('click',async()=>{S.settings.sound=!S.settings.sound;if(!S.settings.sound)stopAudio();header();try{await S.store?.setMeta({id:'settings',...S.settings});}catch(e){issue(e);}});
window.addEventListener('pagehide',()=>{clearTimeout(S.timer);stopAudio();});
document.addEventListener('visibilitychange',()=>{if(document.hidden){stopAudio();clearTimeout(S.timer);}});
async function boot(){
 $('#brandBunny').innerHTML=bunny('wave');document.querySelectorAll('[data-icon]').forEach(el=>el.innerHTML=icon(el.dataset.icon));if(DEMO){$('#legacyLink').href='./index.html?demo=1&mode=local#/home';$('.ws-brand').href='./word-studio.html?demo=1';}
 try{S.store=await openStore(DEMO);}catch{S.notes.push('브라우저 저장소를 사용할 수 없어 임시 학습만 가능해요.');}
 await loadAll();if(S.words.some(w=>w._packId==='legacy'))S.pack='legacy';else{const personal=S.words.find(w=>!S.packs.get(w._packId)?.pack.sample);if(personal)S.pack=personal._packId;}
 try{broadcast=new BroadcastChannel(DEMO?'heather-studio-demo':'heather-studio');broadcast.onmessage=()=>{if(S.view!=='play'&&!dialog.open)refreshLocal().then(()=>render()).catch(issue);};}catch{}
 render('home');
}
boot().catch(e=>{header();main.innerHTML=`<div class="ws-empty"><h1>단어를 불러오지 못했어요.</h1><p>${E(e.message)}</p>${action('reload','다시 시도','primary')}<a href="./index.html#/home">기존 모험으로 돌아가기</a></div>`;});
